window.productsData = [
    // =========================
    // HOMBRE
    // =========================
    {
        section: "trending",
        brand: "NIKE",
        name: "ZAPATOS AIR ZOOM HOMBRE",
        price: 145,
        priceLabel: "$145,00",
        image: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?q=80&w=400",
        alt: "Zapatos Nike hombre",
        badge: true,
        gender: "male",
        activity: "running",
        line: "calzado"
    },
    {
        section: "movement",
        brand: "ADIDAS",
        name: "CAMISETA DEPORTIVA HOMBRE",
        price: 55,
        priceLabel: "$55,00",
        image: "https://images.unsplash.com/photo-1499713907394-43c9d094ac2e?q=80&w=806&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3Dq=80&w=400",
        alt: "Camiseta deportiva hombre",
        badge: false,
        gender: "male",
        activity: "entrenar",
        line: "camiseta"
    },
    {
        section: "trending",
        brand: "PUMA",
        name: "SHORTS TRAINING HOMBRE",
        price: 48,
        priceLabel: "$48,00",
        image: "https://plus.unsplash.com/premium_photo-1727443876790-f8e4bfd40a0c?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3Dq=80&w=400",
        alt: "Shorts training hombre",
        badge: false,
        gender: "male",
        activity: "entrenar",
        line: "shorts"
    },
    {
        section: "movement",
        brand: "UNDER ARMOUR",
        name: "SUDADERA TECH HOMBRE",
        price: 89,
        priceLabel: "$89,00",
        image: "https://images.pexels.com/photos/5667925/pexels-photo-5667925.jpeg",
        alt: "Sudadera hombre",
        badge: true,
        gender: "male",
        activity: "casual",
        line: "sudadera"
    },
    {
        section: "trending",
        brand: "NEW BALANCE",
        name: "PANTALÓN SPORT HOMBRE",
        price: 68,
        priceLabel: "$68,00",
        image: "https://images.pexels.com/photos/13958659/pexels-photo-13958659.jpeg",
        alt: "Pantalón sport hombre",
        badge: false,
        gender: "male",
        activity: "lifestyle",
        line: "pantalon"
    },
    {
        section: "movement",
        brand: "NIKE",
        name: "CAMISETA FÚTBOL HOMBRE",
        price: 62,
        priceLabel: "$62,00",
        image: "https://images.pexels.com/photos/36217788/pexels-photo-36217788.jpeg",
        alt: "Camiseta fútbol hombre",
        badge: true,
        gender: "male",
        activity: "futbol",
        line: "camiseta"
    },
    {
        section: "trending",
        brand: "ADIDAS",
        name: "ZAPATOS URBAN HOMBRE",
        price: 130,
        priceLabel: "$130,00",
        image: "https://images.unsplash.com/photo-1600185365483-26d7a4cc7519?q=80&w=400",
        alt: "Zapatos urbanos hombre",
        badge: false,
        gender: "male",
        activity: "lifestyle",
        line: "calzado"
    },
    {
        section: "movement",
        brand: "PUMA",
        name: "PANTALÓN JOGGER HOMBRE",
        price: 72,
        priceLabel: "$72,00",
        image: "https://images.pexels.com/photos/30710032/pexels-photo-30710032.jpeg",
        alt: "Jogger hombre",
        badge: false,
        gender: "male",
        activity: "casual",
        line: "pantalon"
    },
    {
        section: "trending",
        brand: "REEBOK",
        name: "SUDADERA RUN HOMBRE",
        price: 84,
        priceLabel: "$84,00",
        image: "https://images.pexels.com/photos/7596720/pexels-photo-7596720.jpeg",
        alt: "Sudadera running hombre",
        badge: true,
        gender: "male",
        activity: "running",
        line: "sudadera"
    },
    {
        section: "movement",
        brand: "ASICS",
        name: "SHORTS RUNNING HOMBRE",
        price: 44,
        priceLabel: "$44,00",
        image: "https://images.pexels.com/photos/31381392/pexels-photo-31381392.jpeg",
        alt: "Shorts running hombre",
        badge: false,
        gender: "male",
        activity: "running",
        line: "shorts"
    },

    // =========================
    // MUJER
    // =========================
    {
        section: "trending",
        brand: "NIKE",
        name: "LEGGINGS SPORT MUJER",
        price: 75,
        priceLabel: "$75,00",
        image: "https://images.pexels.com/photos/18932214/pexels-photo-18932214.jpeg",
        alt: "Leggings mujer",
        badge: true,
        gender: "female",
        activity: "entrenar",
        line: "pantalon"
    },
    {
        section: "movement",
        brand: "ADIDAS",
        name: "CAMISETA TRAINING MUJER",
        price: 52,
        priceLabel: "$52,00",
        image: "https://images.pexels.com/photos/13451901/pexels-photo-13451901.jpeg",
        alt: "Camiseta training mujer",
        badge: false,
        gender: "female",
        activity: "entrenar",
        line: "camiseta"
    },
    {
        section: "trending",
        brand: "PUMA",
        name: "ZAPATOS RUNNING MUJER",
        price: 138,
        priceLabel: "$138,00",
        image: "https://images.unsplash.com/photo-1460353581641-37baddab0fa2?q=80&w=400",
        alt: "Zapatos running mujer",
        badge: true,
        gender: "female",
        activity: "running",
        line: "calzado"
    },
    {
        section: "movement",
        brand: "UNDER ARMOUR",
        name: "SUDADERA ACTIVE MUJER",
        price: 86,
        priceLabel: "$86,00",
        image: "https://images.unsplash.com/photo-1529139574466-a303027c1d8b?q=80&w=400",
        alt: "Sudadera active mujer",
        badge: false,
        gender: "female",
        activity: "casual",
        line: "sudadera"
    },
    {
        section: "trending",
        brand: "NEW BALANCE",
        name: "SHORTS FITNESS MUJER",
        price: 42,
        priceLabel: "$42,00",
        image: "https://images.pexels.com/photos/29242426/pexels-photo-29242426.jpeg",
        alt: "Shorts fitness mujer",
        badge: false,
        gender: "female",
        activity: "entrenar",
        line: "shorts"
    },
    {
        section: "movement",
        brand: "NIKE",
        name: "CAMISETA LIFESTYLE MUJER",
        price: 58,
        priceLabel: "$58,00",
        image: "https://images.pexels.com/photos/11394564/pexels-photo-11394564.jpeg",
        alt: "Camiseta lifestyle mujer",
        badge: true,
        gender: "female",
        activity: "lifestyle",
        line: "camiseta"
    },
    {
        section: "trending",
        brand: "ADIDAS",
        name: "PANTALÓN JOGGER MUJER",
        price: 70,
        priceLabel: "$70,00",
        image: "https://images.pexels.com/photos/33327516/pexels-photo-33327516.jpeg",
        alt: "Jogger mujer",
        badge: false,
        gender: "female",
        activity: "casual",
        line: "pantalon"
    },
    {
        section: "movement",
        brand: "PUMA",
        name: "ZAPATOS CASUAL MUJER",
        price: 122,
        priceLabel: "$122,00",
        image: "https://images.pexels.com/photos/27426618/pexels-photo-27426618.jpeg",
        alt: "Zapatos casual mujer",
        badge: true,
        gender: "female",
        activity: "casual",
        line: "calzado"
    },
    {
        section: "trending",
        brand: "REEBOK",
        name: "SUDADERA RUN MUJER",
        price: 81,
        priceLabel: "$81,00",
        image: "https://images.pexels.com/photos/1040424/pexels-photo-1040424.jpeg",
        alt: "Sudadera run mujer",
        badge: false,
        gender: "female",
        activity: "running",
        line: "sudadera"
    },
    {
        section: "movement",
        brand: "ASICS",
        name: "SHORTS RUNNING MUJER",
        price: 43,
        priceLabel: "$43,00",
        image: "https://images.pexels.com/photos/33096784/pexels-photo-33096784.jpeg",
        alt: "Shorts running mujer",
        badge: false,
        gender: "female",
        activity: "running",
        line: "shorts"
    },

    // =========================
    // NIÑOS
    // =========================
    {
        section: "trending",
        brand: "NIKE",
        name: "ZAPATOS RUNNING KIDS",
        price: 78,
        priceLabel: "$78,00",
        image: "https://images.unsplash.com/photo-1514989940723-e8e51635b782?q=80&w=400",
        alt: "Zapatos running niños",
        badge: true,
        gender: "nino",
        activity: "running",
        line: "calzado"
    },
    {
        section: "movement",
        brand: "ADIDAS",
        name: "CAMISETA FÚTBOL NIÑOS",
        price: 42,
        priceLabel: "$42,00",
        image: "https://images.unsplash.com/photo-1517466787929-bc90951d0974?q=80&w=400",
        alt: "Camiseta fútbol niños",
        badge: false,
        gender: "nino",
        activity: "futbol",
        line: "camiseta"
    },
    {
        section: "trending",
        brand: "PUMA",
        name: "SHORTS TRAINING KIDS",
        price: 35,
        priceLabel: "$35,00",
        image: "https://osakaworld.com/cdn/shop/files/TRN00018_6001_1_Kids_Training_Short_S_REC_Royal_Blue.jpg?v=1770304420",
        alt: "Shorts training niños",
        badge: false,
        gender: "nino",
        activity: "entrenar",
        line: "shorts"
    },
    {
        section: "movement",
        brand: "UNDER ARMOUR",
        name: "SUDADERA ACTIVE KIDS",
        price: 56,
        priceLabel: "$56,00",
        image: "https://images.puma.com/image/upload/f_auto,q_auto,b_rgb:fafafa,w_750,h_750/global/527688/01/mod01/fnd/PNA/fmt/png/Sudadera-con-capucha-Active-Sports-para-ni%C3%B1os-grandes",
        alt: "Sudadera active niños",
        badge: true,
        gender: "nino",
        activity: "casual",
        line: "sudadera"
    },
    {
        section: "trending",
        brand: "NEW BALANCE",
        name: "PANTALÓN SPORT NIÑOS",
        price: 48,
        priceLabel: "$48,00",
        image: "https://m.media-amazon.com/images/I/51A8vOLu8ZS._AC_SX569_.jpg",
        alt: "Pantalón sport niños",
        badge: false,
        gender: "nino",
        activity: "lifestyle",
        line: "pantalon"
    },
    {
        section: "movement",
        brand: "NIKE",
        name: "CAMISETA RUN JR",
        price: 39,
        priceLabel: "$39,00",
        image: "https://timsecuador.com/wp-content/uploads/2023/11/IMG_7508-copia-scaled-1-1489x1536.webp",
        alt: "Camiseta running junior",
        badge: false,
        gender: "nino",
        activity: "running",
        line: "camiseta"
    },
    {
        section: "trending",
        brand: "ADIDAS",
        name: "ZAPATOS URBAN KIDS",
        price: 82,
        priceLabel: "$82,00",
        image: "https://conceptos.shop/cdn/shop/files/1172402-2.jpg?v=1740544823&width=533",
        alt: "Zapatos urbanos niños",
        badge: true,
        gender: "nino",
        activity: "casual",
        line: "calzado"
    },
    {
        section: "movement",
        brand: "PUMA",
        name: "SHORTS DEPORTIVOS NIÑOS",
        price: 33,
        priceLabel: "$33,00",
        image: "https://www.skole.ec/1063-large_default/short-deportivo-ninos-kinder.jpg",
        alt: "Shorts deportivos niños",
        badge: false,
        gender: "nino",
        activity: "futbol",
        line: "shorts"
    },
    {
        section: "trending",
        brand: "REEBOK",
        name: "SUDADERA RUN KIDS",
        price: 54,
        priceLabel: "$54,00",
        image: "https://base.net/cdn/shop/files/3-original_c0b8da19-cb18-4ccc-8634-12be2a089b2c.jpg?v=1749665553&width=860",
        alt: "Sudadera run niños",
        badge: false,
        gender: "nino",
        activity: "running",
        line: "sudadera"
    },
    {
        section: "movement",
        brand: "ASICS",
        name: "PANTALÓN JOGGER JR",
        price: 46,
        priceLabel: "$46,00",
        image: "https://k-swiss.com.mx/cdn/shop/files/ventiapp-image--c01cc551-00ab-4536-adf5-5b433dd0a40a_2_1_2025_18_38_53_489.jpg?v=1736963700",
        alt: "Pantalón jogger junior",
        badge: true,
        gender: "nino",
        activity: "entrenar",
        line: "pantalon"
    }
];